# Generated by Django 6.0.3 on 2026-04-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_artist_rename_release_year_product_year_of_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='art_photo'),
        ),
    ]
