# Generated by Django 6.0.3 on 2026-04-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='release_year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
